server:
  port: 28888
management:
  context-path: /admin
custom:
  boot:
    async:
      executor:
        thread-name-prefix: async-thread
        thread-group-name: async-thread-group
        pool-size: 100
    profile:
      enabled: true
      log-frequency: 10
      warning-threshold: 1000
      method-name-patterns:
        - test.*
        - .*printCurrentTimestamp.*

spring:
  aop:
    proxy-target-class: true